### PR TITLE
Update julia-snail.el

### PR DESCRIPTION
**Pull request by norci**
changed var julia-snail--server-file from const to custom.

in order to be used in remote server.

### CODE REVIEW

**Comment by gcv** [comment]
@norci: Hey, sorry about not reacting to your PR. It's very clever, but I have a more explicit implementation for remote REPLs in mind. It will be released as soon as I find time to work on it.

**Comment by norci** [comment]
I'm glad to hear that.

btw, if the remote REPL is connected through ssh,  what about use `tmux` to protect it from reconnect?

**Comment by gcv** [comment]
While I use tmux all the time, I'm not super-proficient with it. Does it have some kind of headless mode? There's also mosh, but it's also terminal-centric.

**Comment by norci** [comment]
I don't think tmux has a headless mode.

This command might be good enough to run julia:
`tmux new -AD -s jl -- julia args`

https://github.com/tmux/tmux/wiki/Getting-Started
> By default, the first session will be called 0, the second 1 and so on. new-session allows a name to be specified for the session with the -s flag:
> 
> $ tmux new -smysession
> 
> This creates a new session called mysession. A command may be given instead of running a shell by passing additional arguments. If one argument is given, tmux will pass it to the shell, if more than one it runs the command directly. For example these run emacs(1):
> 
> $ tmux new 'emacs ~/.tmux.conf'
> 
> Or:
> 
> $ tmux new -- emacs ~/.tmux.conf
> 
> The new-session command has a -A flag to attach to an existing session if it exists, or create a new one if it does not. For a session named mysession:
>
> $ tmux new -Asmysession
>
> The -D flag may be added to make new-session also behave like attach-session with -d and detach any other clients attached to the session.

**Comment by gcv** [comment]
Interesting. That's a really good idea. It leaves a couple of questions. One, is there a good way on the Elisp side to detect a disconnect and automatically attempt a reconnect? (Probably.) Two, what about orphaned tmux sessions on the remote side? (Probably have to ignore them; yuck?)

**Comment by norci** [comment]
I have no idea about elisp.

about tmux. the session name should be defined in a variable, so the user can customize it.
then orphaned session should be handled by the user too.

**Comment by gcv** [comment]
Remote REPL support merged in commit 47f1b12. Documentation: https://github.com/gcv/julia-snail#remote-repls

I decided against supporting tmux right now. It would take too much work to write the code to properly restore state on the Emacs side after connecting to an existing REPL.

**Pull request closed without merging**
